// Autogenerated file, do not edit directly

// WordPress Dependencies.
import { addAction, addFilter } from '@wordpress/hooks';

// Divi Dependencies.
import { iconList } from '@divi/icon-library';

// Icons.
import * as arrowUp from './arrow_up/arrow_up';
import * as arrowDown from './arrow_down/arrow_down';
import * as arrowLeft from './arrow_left/arrow_left';
import * as arrowRight from './arrow_right/arrow_right';
import * as arrowLeftUp from './arrow_left-up/arrow_left-up';
import * as arrowRightUp from './arrow_right-up/arrow_right-up';
import * as arrowRightDown from './arrow_right-down/arrow_right-down';
import * as arrowLeftDown from './arrow_left-down/arrow_left-down';
import * as arrowUpDown from './arrow-up-down/arrow-up-down';
import * as arrowUpDownAlt from './arrow_up-down_alt/arrow_up-down_alt';
import * as arrowLeftRightAlt from './arrow_left-right_alt/arrow_left-right_alt';
import * as arrowLeftRight from './arrow_left-right/arrow_left-right';
import * as arrowExpandAlt2 from './arrow_expand_alt2/arrow_expand_alt2';
import * as arrowExpandAlt from './arrow_expand_alt/arrow_expand_alt';
import * as arrowCondense from './arrow_condense/arrow_condense';
import * as arrowExpand from './arrow_expand/arrow_expand';
import * as arrowMove from './arrow_move/arrow_move';
import * as caretUp from './caret-up/caret-up';
import * as caretDown from './caret-down/caret-down';
import * as caretLeft from './caret-left/caret-left';
import * as caretRight from './caret-right/caret-right';
import * as caretTwoUp from './caret-two-up/caret-two-up';
import * as caretTwoDown from './caret-two-down/caret-two-down';
import * as caretTwoLeft from './caret-two-left/caret-two-left';
import * as caretTwoRight from './caret-two-right/caret-two-right';
import * as caretLineUp from './caret-line-up/caret-line-up';
import * as caretLineDown from './caret-line-down/caret-line-down';
import * as caretLineLeft from './caret-line-left/caret-line-left';
import * as caretLineRight from './caret-line-right/caret-line-right';
import * as caretLineTwoUp from './caret-line-two-up/caret-line-two-up';
import * as caretLineTwoDown from './caret-line-two-down/caret-line-two-down';
import * as caretLineTwoLeft from './caret-line-two-left/caret-line-two-left';
import * as caretLineTwoRight from './caret-line-two-right/caret-line-two-right';
import * as triangleUp from './triangle-up/triangle-up';
import * as triangleDown from './triangle-down/triangle-down';
import * as triangleLeft from './triangle-left/triangle-left';
import * as triangleRight from './triangle-right/triangle-right';
import * as triangleLineUp from './triangle-line-up/triangle-line-up';
import * as triangleLineDown from './triangle-line-down/triangle-line-down';
import * as triangleLineLeft from './triangle-line-left/triangle-line-left';
import * as triangleLineRight from './triangle-line-right/triangle-line-right';
import * as arrowBack from './arrow_back/arrow_back';
import * as minusMark from './minus-mark/minus-mark';
import * as plusMark from './plus-mark/plus-mark';
import * as closeMark from './close-mark/close-mark';
import * as checkMark from './check-mark/check-mark';
import * as minusLine from './minus-line/minus-line';
import * as plusLine from './plus-line/plus-line';
import * as closeLine from './close-line/close-line';
import * as checkLine from './check-line/check-line';
import * as iconZoomOutAlt from './icon_zoom-out_alt/icon_zoom-out_alt';
import * as iconZoomInAlt from './icon_zoom-in_alt/icon_zoom-in_alt';
import * as searchRight from './search-right/search-right';
import * as iconBoxEmpty from './icon_box-empty/icon_box-empty';
import * as iconBoxSelected from './icon_box-selected/icon_box-selected';
import * as collapse from './collapse/collapse';
import * as expand from './expand/expand';
import * as iconBoxChecked from './icon_box-checked/icon_box-checked';
import * as iconCircleEmpty from './icon_circle-empty/icon_circle-empty';
import * as iconCircleSlelected from './icon_circle-slelected/icon_circle-slelected';
import * as iconStopAlt2 from './icon_stop_alt2/icon_stop_alt2';
import * as iconStop from './icon_stop/icon_stop';
import * as iconPauseAlt2 from './icon_pause_alt2/icon_pause_alt2';
import * as iconPause from './icon_pause/icon_pause';
import * as iconMenu from './icon_menu/icon_menu';
import * as iconMenuSquareAlt2 from './icon_menu-square_alt2/icon_menu-square_alt2';
import * as iconMenuCircleAlt2 from './icon_menu-circle_alt2/icon_menu-circle_alt2';
import * as iconUl from './icon_ul/icon_ul';
import * as iconOl from './icon_ol/icon_ol';
import * as iconAdjustHoriz from './icon_adjust-horiz/icon_adjust-horiz';
import * as iconAdjustVert from './icon_adjust-vert/icon_adjust-vert';
import * as iconDocumentAlt from './icon_document_alt/icon_document_alt';
import * as iconDocumentsAlt from './icon_documents_alt/icon_documents_alt';
import * as pencil from './pencil/pencil';
import * as iconPencilEditAlt from './icon_pencil-edit_alt/icon_pencil-edit_alt';
import * as pencilEdit from './pencil-edit/pencil-edit';
import * as iconFolderAlt from './icon_folder-alt/icon_folder-alt';
import * as iconFolderOpenAlt from './icon_folder-open_alt/icon_folder-open_alt';
import * as iconFolderAddAlt from './icon_folder-add_alt/icon_folder-add_alt';
import * as toggle from './toggle/toggle';
import * as countdown from './countdown/countdown';
import * as iconErrorCircleAlt from './icon_error-circle_alt/icon_error-circle_alt';
import * as iconErrorTriangleAlt from './icon_error-triangle_alt/icon_error-triangle_alt';
import * as iconCommentAlt from './icon_comment_alt/icon_comment_alt';
import * as iconChatAlt from './icon_chat_alt/icon_chat_alt';
import * as iconVolMuteAlt from './icon_vol-mute_alt/icon_vol-mute_alt';
import * as iconVolumeLowAlt from './icon_volume-low_alt/icon_volume-low_alt';
import * as iconVolumeHighAlt from './icon_volume-high_alt/icon_volume-high_alt';
import * as iconQuotations from './icon_quotations/icon_quotations';
import * as iconQuotationsAlt2 from './icon_quotations_alt2/icon_quotations_alt2';
import * as iconClockAlt from './icon_clock_alt/icon_clock_alt';
import * as iconLockAlt from './icon_lock_alt/icon_lock_alt';
import * as cta from './cta/cta';
import * as filteredPortfolio from './filtered-portfolio/filtered-portfolio';
import * as blurb from './blurb/blurb';
import * as circleCounter from './circle-counter/circle-counter';
import * as numberCounter from './number-counter/number-counter';
import * as pricingTable from './pricing-table/pricing-table';
import * as portfolio from './portfolio/portfolio';
import * as tabs from './tabs/tabs';
import * as subscribe from './subscribe/subscribe';
import * as slider from './slider/slider';
import * as sidebar from './sidebar/sidebar';
import * as share from './share/share';
import * as divider from './divider/divider';
import * as header from './header/header';
import * as beaker3 from './beaker3/beaker3';
import * as beaker4 from './beaker4/beaker4';
import * as beaker5 from './beaker5/beaker5';
import * as caweb from './caweb/caweb';
import * as candleAlt from './candle-alt/candle-alt';
import * as iconLockOpenAlt from './icon_lock-open_alt/icon_lock-open_alt';
import * as iconKeyAlt from './icon_key_alt/icon_key_alt';
import * as iconCloudAlt from './icon_cloud_alt/icon_cloud_alt';
import * as iconCloudUploadAlt from './icon_cloud-upload_alt/icon_cloud-upload_alt';
import * as iconCloudDownloadAlt from './icon_cloud-download_alt/icon_cloud-download_alt';
import * as iconLightbulbAlt from './icon_lightbulb_alt/icon_lightbulb_alt';
import * as iconGiftAlt from './icon_gift_alt/icon_gift_alt';
import * as iconHouseAlt from './icon_house_alt/icon_house_alt';
import * as science from './science/science';
import * as iconLaptop from './icon_laptop/icon_laptop';
import * as iconCameraAlt from './icon_camera_alt/icon_camera_alt';
import * as iconMailAlt from './icon_mail_alt/icon_mail_alt';
import * as iconConeAlt from './icon_cone_alt/icon_cone_alt';
import * as iconRibbonAlt from './icon_ribbon_alt/icon_ribbon_alt';
import * as iconBagAlt from './icon_bag_alt/icon_bag_alt';
import * as iconCreditcard from './icon_creditcard/icon_creditcard';
import * as iconCartAlt from './icon_cart_alt/icon_cart_alt';
import * as iconPaperclip from './icon_paperclip/icon_paperclip';
import * as iconTagAlt from './icon_tag_alt/icon_tag_alt';
import * as iconTagsAlt from './icon_tags_alt/icon_tags_alt';
import * as iconTrashAlt from './icon_trash_alt/icon_trash_alt';
import * as iconCursorAlt from './icon_cursor_alt/icon_cursor_alt';
import * as iconMicAlt from './icon_mic_alt/icon_mic_alt';
import * as iconCompassAlt from './icon_compass_alt/icon_compass_alt';
import * as iconPinAlt from './icon_pin_alt/icon_pin_alt';
import * as iconPushpinAlt from './icon_pushpin_alt/icon_pushpin_alt';
import * as iconMapAlt from './icon_map_alt/icon_map_alt';
import * as iconDrawerAlt from './icon_drawer_alt/icon_drawer_alt';
import * as iconToolboxAlt from './icon_toolbox_alt/icon_toolbox_alt';
import * as iconBookAlt from './icon_book_alt/icon_book_alt';
import * as iconCalendar from './icon_calendar/icon_calendar';
import * as film from './film/film';
import * as table from './table/table';
import * as iconContactsAlt from './icon_contacts_alt/icon_contacts_alt';
import * as iconHeadphones from './icon_headphones/icon_headphones';
import * as iconRefresh from './icon_refresh/icon_refresh';
import * as iconLinkAlt from './icon_link_alt/icon_link_alt';
import * as iconLink from './icon_link/icon_link';
import * as iconLoading from './icon_loading/icon_loading';
import * as iconBlocked from './icon_blocked/icon_blocked';
import * as iconArchiveAlt from './icon_archive_alt/icon_archive_alt';
import * as iconHeartAlt from './icon_heart_alt/icon_heart_alt';
import * as iconStarAlt from './icon_star_alt/icon_star_alt';
import * as iconStarHalfAlt from './icon_star-half_alt/icon_star-half_alt';
import * as iconStarHalf from './icon_star-half/icon_star-half';
import * as tools from './tools/tools';
import * as iconCog from './icon_cog/icon_cog';
import * as iconCogs from './icon_cogs/icon_cogs';
import * as arrowFillUp from './arrow-fill-up/arrow-fill-up';
import * as arrowFillDown from './arrow-fill-down/arrow-fill-down';
import * as arrowFillLeft from './arrow-fill-left/arrow-fill-left';
import * as arrowFillRight from './arrow-fill-right/arrow-fill-right';
import * as arrowFillLeftUp from './arrow-fill-left-up/arrow-fill-left-up';
import * as arrowFillRightUp from './arrow-fill-right-up/arrow-fill-right-up';
import * as arrowFillRightDown from './arrow-fill-right-down/arrow-fill-right-down';
import * as arrowFillLeftDown from './arrow-fill-left-down/arrow-fill-left-down';
import * as arrowCondenseAlt from './arrow_condense_alt/arrow_condense_alt';
import * as arrowExpandAlt3 from './arrow_expand_alt3/arrow_expand_alt3';
import * as caretFillUp from './caret-fill-up/caret-fill-up';
import * as caretFillDown from './caret-fill-down/caret-fill-down';
import * as caretFillLeft from './caret-fill-left/caret-fill-left';
import * as caretFillRight from './caret-fill-right/caret-fill-right';
import * as caretFillTwoUp from './caret-fill-two-up/caret-fill-two-up';
import * as caretFillTwoDown from './caret-fill-two-down/caret-fill-two-down';
import * as caretFillTwoLeft from './caret-fill-two-left/caret-fill-two-left';
import * as caretFillTwoRight from './caret-fill-two-right/caret-fill-two-right';
import * as triangleFillUp from './triangle-fill-up/triangle-fill-up';
import * as triangleFillDown from './triangle-fill-down/triangle-fill-down';
import * as triangleFillLeft from './triangle-fill-left/triangle-fill-left';
import * as triangleFillRight from './triangle-fill-right/triangle-fill-right';
import * as minusFill from './minus-fill/minus-fill';
import * as plusFill from './plus-fill/plus-fill';
import * as closeFill from './close-fill/close-fill';
import * as checkFill from './check-fill/check-fill';
import * as iconZoomOut from './icon_zoom-out/icon_zoom-out';
import * as iconZoomIn from './icon_zoom-in/icon_zoom-in';
import * as iconStopAlt from './icon_stop_alt/icon_stop_alt';
import * as iconMenuSquareAlt from './icon_menu-square_alt/icon_menu-square_alt';
import * as iconMenuCircleAlt from './icon_menu-circle_alt/icon_menu-circle_alt';
import * as iconDocument from './icon_document/icon_document';
import * as iconDocuments from './icon_documents/icon_documents';
import * as iconPencilAlt from './icon_pencil_alt/icon_pencil_alt';
import * as iconFolder from './icon_folder/icon_folder';
import * as folder from './folder/folder';
import * as iconFolderAdd from './icon_folder-add/icon_folder-add';
import * as iconFolderUpload from './icon_folder_upload/icon_folder_upload';
import * as iconFolderDownload from './icon_folder_download/icon_folder_download';
import * as iconErrorCircle from './icon_error-circle/icon_error-circle';
import * as warningFill from './warning-fill/warning-fill';
import * as warningTriangle from './warning-triangle/warning-triangle';
import * as questionFill from './question-fill/question-fill';
import * as iconComment from './icon_comment/icon_comment';
import * as iconChat from './icon_chat/icon_chat';
import * as iconVolMute from './icon_vol-mute/icon_vol-mute';
import * as iconVolumeLow from './icon_volume-low/icon_volume-low';
import * as volume from './volume/volume';
import * as quoteFill from './quote-fill/quote-fill';
import * as iconClock from './icon_clock/icon_clock';
import * as iconLock from './icon_lock/icon_lock';
import * as iconLockOpen from './icon_lock-open/icon_lock-open';
import * as iconKey from './icon_key/icon_key';
import * as iconCloud from './icon_cloud/icon_cloud';
import * as iconCloudUpload from './icon_cloud-upload/icon_cloud-upload';
import * as iconCloudDownload from './icon_cloud-download/icon_cloud-download';
import * as lightbulb from './lightbulb/lightbulb';
import * as iconGift from './icon_gift/icon_gift';
import * as iconHouse from './icon_house/icon_house';
import * as iconMail from './icon_mail/icon_mail';
import * as iconCone from './icon_cone/icon_cone';
import * as iconRibbon from './icon_ribbon/icon_ribbon';
import * as iconBag from './icon_bag/icon_bag';
import * as iconCart from './icon_cart/icon_cart';
import * as iconTag from './icon_tag/icon_tag';
import * as tags from './tags/tags';
import * as iconTrash from './icon_trash/icon_trash';
import * as iconCursor from './icon_cursor/icon_cursor';
import * as mic from './mic/mic';
import * as iconCompass from './icon_compass/icon_compass';
import * as location from './location/location';
import * as pushpin from './pushpin/pushpin';
import * as map from './map/map';
import * as drawer from './drawer/drawer';
import * as book from './book/book';
import * as contacts from './contacts/contacts';
import * as archive from './archive/archive';
import * as iconHeart from './icon_heart/icon_heart';
import * as grid from './grid/grid';
import * as music from './music/music';
import * as iconPauseAlt from './icon_pause_alt/icon_pause_alt';
import * as iconPhone from './icon_phone/icon_phone';
import * as iconUpload from './icon_upload/icon_upload';
import * as iconDownload from './icon_download/icon_download';
import * as barCounters from './bar-counters/bar-counters';
import * as audio from './audio/audio';
import * as accordion from './accordion/accordion';
import * as socialGoogleplus from './social_googleplus/social_googleplus';
import * as socialTumblr from './social_tumblr/social_tumblr';
import * as socialTumbleupon from './social_tumbleupon/social_tumbleupon';
import * as socialWordpress from './social_wordpress/social_wordpress';
import * as socialDribbble from './social_dribbble/social_dribbble';
import * as socialDeviantart from './social_deviantart/social_deviantart';
import * as socialMyspace from './social_myspace/social_myspace';
import * as socialSkype from './social_skype/social_skype';
import * as socialPicassa from './social_picassa/social_picassa';
import * as socialGoogledrive from './social_googledrive/social_googledrive';
import * as socialFlickr from './social_flickr/social_flickr';
import * as socialBlogger from './social_blogger/social_blogger';
import * as socialSpotify from './social_spotify/social_spotify';
import * as socialDelicious from './social_delicious/social_delicious';
import * as socialFacebookCircle from './social_facebook_circle/social_facebook_circle';
import * as socialTwitterCircle from './social_twitter_circle/social_twitter_circle';
import * as socialPinterestCircle from './social_pinterest_circle/social_pinterest_circle';
import * as socialGoogleplusCircle from './social_googleplus_circle/social_googleplus_circle';
import * as socialTumblrCircle from './social_tumblr_circle/social_tumblr_circle';
import * as socialStumbleuponCircle from './social_stumbleupon_circle/social_stumbleupon_circle';
import * as socialWordpressCircle from './social_wordpress_circle/social_wordpress_circle';
import * as socialInstagramCircle from './social_instagram_circle/social_instagram_circle';
import * as socialDribbbleCircle from './social_dribbble_circle/social_dribbble_circle';
import * as socialVimeoCircle from './social_vimeo_circle/social_vimeo_circle';
import * as socialLinkedinCircle from './social_linkedin_circle/social_linkedin_circle';
import * as socialRssCircle from './social_rss_circle/social_rss_circle';
import * as socialDeviantartCircle from './social_deviantart_circle/social_deviantart_circle';
import * as socialShareCircle from './social_share_circle/social_share_circle';
import * as socialMyspaceCircle from './social_myspace_circle/social_myspace_circle';
import * as socialSkypeCircle from './social_skype_circle/social_skype_circle';
import * as socialYoutubeCircle from './social_youtube_circle/social_youtube_circle';
import * as socialPicassaCircle from './social_picassa_circle/social_picassa_circle';
import * as socialGoogledriveAlt2 from './social_googledrive_alt2/social_googledrive_alt2';
import * as socialFlickrCircle from './social_flickr_circle/social_flickr_circle';
import * as socialBloggerCircle from './social_blogger_circle/social_blogger_circle';
import * as socialSpotifyCircle from './social_spotify_circle/social_spotify_circle';
import * as socialDeliciousCircle from './social_delicious_circle/social_delicious_circle';
import * as socialTumblrSquare from './social_tumblr_square/social_tumblr_square';
import * as socialStumbleuponSquare from './social_stumbleupon_square/social_stumbleupon_square';
import * as socialWordpressSquare from './social_wordpress_square/social_wordpress_square';
import * as socialInstagramSquare from './social_instagram_square/social_instagram_square';
import * as socialDribbbleSquare from './social_dribbble_square/social_dribbble_square';
import * as socialRssSquare from './social_rss_square/social_rss_square';
import * as socialDeviantartSquare from './social_deviantart_square/social_deviantart_square';
import * as socialShareSquare from './social_share_square/social_share_square';
import * as socialMyspaceSquare from './social_myspace_square/social_myspace_square';
import * as socialSkypeSquare from './social_skype_square/social_skype_square';
import * as socialPicassaSquare from './social_picassa_square/social_picassa_square';
import * as socialGoogledriveSquare from './social_googledrive_square/social_googledrive_square';
import * as socialFlickrSquare from './social_flickr_square/social_flickr_square';
import * as socialBloggerSquare from './social_blogger_square/social_blogger_square';
import * as socialSpotifySquare from './social_spotify_square/social_spotify_square';
import * as socialDeliciousSquare from './social_delicious_square/social_delicious_square';
import * as wallet from './wallet/wallet';
import * as iconShieldAlt from './icon_shield_alt/icon_shield_alt';
import * as iconPercentAlt from './icon_percent_alt/icon_percent_alt';
import * as iconPensAlt from './icon_pens_alt/icon_pens_alt';
import * as iconMugAlt from './icon_mug_alt/icon_mug_alt';
import * as iconLikeAlt from './icon_like_alt/icon_like_alt';
import * as iconGlobeAlt from './icon_globe_alt/icon_globe_alt';
import * as flowchart from './flowchart/flowchart';
import * as iconIdAlt from './icon_id_alt/icon_id_alt';
import * as hourglass from './hourglass/hourglass';
import * as iconGlobe from './icon_globe/icon_globe';
import * as globe from './globe/globe';
import * as iconFloppyAlt from './icon_floppy_alt/icon_floppy_alt';
import * as drive from './drive/drive';
import * as iconClipboard from './icon_clipboard/icon_clipboard';
import * as calculator from './calculator/calculator';
import * as iconFloppy from './icon_floppy/icon_floppy';
import * as iconEasel from './icon_easel/icon_easel';
import * as iconDrive from './icon_drive/icon_drive';
import * as iconDislike from './icon_dislike/icon_dislike';
import * as iconDatareport from './icon_datareport/icon_datareport';
import * as iconCurrency from './icon_currency/icon_currency';
import * as iconCalulator from './icon_calulator/icon_calulator';
import * as iconBuilding from './icon_building/icon_building';
import * as iconDislikeAlt from './icon_dislike_alt/icon_dislike_alt';
import * as currency from './currency/currency';
import * as iconBriefcaseAlt from './icon_briefcase_alt/icon_briefcase_alt';
import * as iconTarget from './icon_target/icon_target';
import * as iconShield from './icon_shield/icon_shield';
import * as searching from './searching/searching';
import * as iconRook from './icon_rook/icon_rook';
import * as iconPuzzleAlt from './icon_puzzle_alt/icon_puzzle_alt';
import * as iconPercent from './icon_percent/icon_percent';
import * as building from './building/building';
import * as iconBriefcase from './icon_briefcase/icon_briefcase';
import * as iconBalance from './icon_balance/icon_balance';
import * as iconWallet from './icon_wallet/icon_wallet';
import * as iconSearch from './icon_search/icon_search';
import * as iconPuzzle from './icon_puzzle/icon_puzzle';
import * as iconPrinter from './icon_printer/icon_printer';
import * as iconPens from './icon_pens/icon_pens';
import * as iconMug from './icon_mug/icon_mug';
import * as iconLike from './icon_like/icon_like';
import * as iconId from './icon_id/icon_id';
import * as iconId2 from './icon_id-2/icon_id-2';
import * as iconFlowchart from './icon_flowchart/icon_flowchart';
import * as logo from './logo/logo';
import * as home from './home/home';
import * as menu from './menu/menu';
import * as apps from './apps/apps';
import * as search from './search/search';
import * as chat from './chat/chat';
import * as capitol from './capitol/capitol';
import * as state from './state/state';
import * as phone from './phone/phone';
import * as email from './email/email';
import * as calendar from './calendar/calendar';
import * as bear from './bear/bear';
import * as lawEnforcement from './law-enforcement/law-enforcement';
import * as justiceLegal from './justice-legal/justice-legal';
import * as atSign from './at-sign/at-sign';
import * as attachment from './attachment/attachment';
import * as zippedFile from './zipped-file/zipped-file';
import * as powerpoint from './powerpoint/powerpoint';
import * as excel from './excel/excel';
import * as word from './word/word';
import * as pdf from './pdf/pdf';
import * as share2 from './share2/share2';
import * as facebook from './facebook/facebook';
import * as linkedin from './linkedin/linkedin';
import * as youtube from './youtube/youtube';
import * as twitter from './twitter/twitter';
import * as pinterest from './pinterest/pinterest';
import * as vimeo from './vimeo/vimeo';
import * as instagram from './instagram/instagram';
import * as flickr from './flickr/flickr';
import * as microsoft from './microsoft/microsoft';
import * as apple from './apple/apple';
import * as android from './android/android';
import * as computer from './computer/computer';
import * as tablet from './tablet/tablet';
import * as smartphone from './smartphone/smartphone';
import * as roadways from './roadways/roadways';
import * as travelCar from './travel-car/travel-car';
import * as travelAir from './travel-air/travel-air';
import * as truckDelivery from './truck-delivery/truck-delivery';
import * as construction from './construction/construction';
import * as barChart from './bar-chart/bar-chart';
import * as pieChart from './pie-chart/pie-chart';
import * as graph from './graph/graph';
import * as server from './server/server';
import * as download from './download/download';
import * as cloudDownload from './cloud-download/cloud-download';
import * as cloudUpload from './cloud-upload/cloud-upload';
import * as shield from './shield/shield';
import * as fire from './fire/fire';
import * as binoculars from './binoculars/binoculars';
import * as compass from './compass/compass';
import * as sos from './sos/sos';
import * as shoppingCart from './shopping-cart/shopping-cart';
import * as videoCamera from './video-camera/video-camera';
import * as camera from './camera/camera';
import * as green from './green/green';
import * as loudSpeaker from './loud-speaker/loud-speaker';
import * as audio2 from './audio2/audio2';
import * as print from './print/print';
import * as medical from './medical/medical';
import * as zoomOut from './zoom-out/zoom-out';
import * as zoomIn from './zoom-in/zoom-in';
import * as important from './important/important';
import * as chatBubbles from './chat-bubbles/chat-bubbles';
import * as call from './call/call';
import * as people from './people/people';
import * as person from './person/person';
import * as userId from './user-id/user-id';
import * as paymentCard from './payment-card/payment-card';
import * as skipBackwards from './skip-backwards/skip-backwards';
import * as play from './play/play';
import * as pause from './pause/pause';
import * as skipForward from './skip-forward/skip-forward';
import * as mail from './mail/mail';
import * as image from './image/image';
import * as house from './house/house';
import * as gear from './gear/gear';
import * as tool from './tool/tool';
import * as time from './time/time';
import * as cal from './cal/cal';
import * as checkList from './check-list/check-list';
import * as document from './document/document';
import * as clipboard from './clipboard/clipboard';
import * as page from './page/page';
import * as readBook from './read-book/read-book';
import * as ccCopyright from './cc-copyright/cc-copyright';
import * as caCapitol from './ca-capitol/ca-capitol';
import * as caState from './ca-state/ca-state';
import * as favorite from './favorite/favorite';
import * as rss from './rss/rss';
import * as roadPin from './road-pin/road-pin';
import * as onlineServices from './online-services/online-services';
import * as link from './link/link';
import * as magnifyGlass from './magnify-glass/magnify-glass';
import * as key from './key/key';
import * as lock from './lock/lock';
import * as info from './info/info';
import * as carouselPrev from './carousel-prev/carousel-prev';
import * as carouselNext from './carousel-next/carousel-next';
import * as arrowPrev from './arrow-prev/arrow-prev';
import * as arrowNext from './arrow-next/arrow-next';
import * as menuToggleClosed from './menu-toggle-closed/menu-toggle-closed';
import * as menuToggleOpen from './menu-toggle-open/menu-toggle-open';
import * as carouselPause from './carousel-pause/carousel-pause';
import * as googlePlus from './google-plus/google-plus';
import * as contactUs from './contact-us/contact-us';
import * as chatBubble from './chat-bubble/chat-bubble';
import * as infoBubble from './info-bubble/info-bubble';
import * as shareButton from './share-button/share-button';
import * as shareFacebook from './share-facebook/share-facebook';
import * as shareEmail from './share-email/share-email';
import * as shareFlickr from './share-flickr/share-flickr';
import * as shareTwitter from './share-twitter/share-twitter';
import * as shareLinkedin from './share-linkedin/share-linkedin';
import * as shareGoogleplus from './share-googleplus/share-googleplus';
import * as shareInstagram from './share-instagram/share-instagram';
import * as sharePinterest from './share-pinterest/share-pinterest';
import * as shareVimeo from './share-vimeo/share-vimeo';
import * as shareYoutube from './share-youtube/share-youtube';
import * as gears from './gears/gears';
import * as briefcase from './briefcase/briefcase';
import * as idea from './idea/idea';
import * as graduate from './graduate/graduate';
import * as images from './images/images';
import * as infoLine from './info-line/info-line';
import * as importantLine from './important-line/important-line';
import * as carouselPlay from './carousel-play/carousel-play';
import * as questionLine from './question-line/question-line';
import * as question from './question/question';
import * as filter from './filter/filter';
import * as calBear from './cal-bear/cal-bear';
import * as hours from './hours/hours';
import * as hoursSecurity from './hours-security/hours-security';
import * as albums from './albums/albums';
import * as brain from './brain/brain';
import * as certificate from './certificate/certificate';
import * as certificateCheck from './certificate-check/certificate-check';
import * as charge from './charge/charge';
import * as chargeCycle from './charge-cycle/charge-cycle';
import * as chargeUnits from './charge-units/charge-units';
import * as city from './city/city';
import * as clock from './clock/clock';
import * as cloudGear from './cloud-gear/cloud-gear';
import * as biohazard from './biohazard/biohazard';
import * as malware from './malware/malware';
import * as cloudServices from './cloud-services/cloud-services';
import * as cloudSync from './cloud-sync/cloud-sync';
import * as code from './code/code';
import * as ear from './ear/ear';
import * as earSlash from './ear-slash/ear-slash';
import * as eye from './eye/eye';
import * as eyeSlash from './eye-slash/eye-slash';
import * as file from './file/file';
import * as fileAudio from './file-audio/file-audio';
import * as fileCertificate from './file-certificate/file-certificate';
import * as fileCheck from './file-check/file-check';
import * as fileCode from './file-code/file-code';
import * as fileCsv from './file-csv/file-csv';
import * as fileDownload from './file-download/file-download';
import * as fileExcel from './file-excel/file-excel';
import * as fileExport from './file-export/file-export';
import * as fileImport from './file-import/file-import';
import * as fileInvoice from './file-invoice/file-invoice';
import * as fileMedical from './file-medical/file-medical';
import * as fileMedicalAlt from './file-medical-alt/file-medical-alt';
import * as filePdf from './file-pdf/file-pdf';
import * as filePowerpoint from './file-powerpoint/file-powerpoint';
import * as filePrescription from './file-prescription/file-prescription';
import * as fileUpload from './file-upload/file-upload';
import * as fileVideo from './file-video/file-video';
import * as fileWord from './file-word/file-word';
import * as fileZip from './file-zip/file-zip';
import * as filterSolid from './filter-solid/filter-solid';
import * as fingerprint from './fingerprint/fingerprint';
import * as fingerprintCheck from './fingerprint-check/fingerprint-check';
import * as hand from './hand/hand';
import * as handMoney from './hand-money/hand-money';
import * as handshake from './handshake/handshake';
import * as institute from './institute/institute';
import * as medicalBubble from './medical-bubble/medical-bubble';
import * as medicalCare from './medical-care/medical-care';
import * as medicalCase from './medical-case/medical-case';
import * as medicalClinic from './medical-clinic/medical-clinic';
import * as medicalCross from './medical-cross/medical-cross';
import * as medicalDoctor from './medical-doctor/medical-doctor';
import * as medicalHeart from './medical-heart/medical-heart';
import * as medicalPills from './medical-pills/medical-pills';
import * as mobile from './mobile/mobile';
import * as proServices from './pro-services/pro-services';
import * as puzzle from './puzzle/puzzle';
import * as puzzlePiece from './puzzle-piece/puzzle-piece';
import * as recycle from './recycle/recycle';
import * as responsive from './responsive/responsive';
import * as responsiveAlt from './responsive-alt/responsive-alt';
import * as securityNetwork from './security-network/security-network';
import * as securitySystem from './security-system/security-system';
import * as shieldCheck from './shield-check/shield-check';
import * as thumbUp from './thumb-up/thumb-up';
import * as trophy from './trophy/trophy';
import * as users from './users/users';
import * as usersAlt from './users-alt/users-alt';
import * as usersDialog from './users-dialog/users-dialog';
import * as usersInteraction from './users-interaction/users-interaction';
import * as video from './video/video';
import * as radiation from './radiation/radiation';
import * as chemicalHazard from './chemical-hazard/chemical-hazard';
import * as danger from './danger/danger';
import * as doNotSign from './do-not-sign/do-not-sign';
import * as earthquake from './earthquake/earthquake';
import * as quakeHouse from './quake-house/quake-house';
import * as quakeHazard from './quake-hazard/quake-hazard';
import * as electricityHazard from './electricity-hazard/electricity-hazard';
import * as flood from './flood/flood';
import * as hazard from './hazard/hazard';
import * as hurricane from './hurricane/hurricane';
import * as seaLevelRise from './sea-level-rise/sea-level-rise';
import * as severeWeather from './severe-weather/severe-weather';
import * as stopFire from './stop-fire/stop-fire';
import * as stopHand from './stop-hand/stop-hand';
import * as tornado from './tornado/tornado';
import * as tsunami from './tsunami/tsunami';
import * as volcano from './volcano/volcano';
import * as warningCircle from './warning-circle/warning-circle';
import * as warningSquare from './warning-square/warning-square';
import * as tent from './tent/tent';
import * as campfire from './campfire/campfire';
import * as dam from './dam/dam';
import * as downloadCloud from './download-cloud/download-cloud';
import * as uploadCloud from './upload-cloud/upload-cloud';
import * as seaLevelRiseAlt from './sea-level-rise-alt/sea-level-rise-alt';
import * as tsunamiAlt from './tsunami-alt/tsunami-alt';
import * as collapseAll from './collapse-all/collapse-all';
import * as signLanguage from './sign-language/sign-language';
import * as drag from './drag/drag';
import * as agriculture from './agriculture/agriculture';
import * as cannabis from './cannabis/cannabis';
import * as angry from './angry/angry';
import * as happy from './happy/happy';
import * as visa from './visa/visa';
import * as mastercard from './mastercard/mastercard';
import * as amexcard from './amexcard/amexcard';
import * as applePay from './apple-pay/apple-pay';
import * as discovercard from './discovercard/discovercard';
import * as paypal from './paypal/paypal';
import * as chrome from './chrome/chrome';
import * as firefox from './firefox/firefox';
import * as ie from './ie/ie';
import * as opera from './opera/opera';
import * as safari from './safari/safari';
import * as bell from './bell/bell';
import * as bookmark from './bookmark/bookmark';
import * as books from './books/books';
import * as reader from './reader/reader';
import * as palette from './palette/palette';
import * as glass from './glass/glass';
import * as heart from './heart/heart';
import * as digging from './digging/digging';
import * as gasPump from './gas-pump/gas-pump';
import * as ideaAlt from './idea-alt/idea-alt';
import * as medal from './medal/medal';
import * as smoking from './smoking/smoking';
import * as noSmoking from './no-smoking/no-smoking';
import * as shareSnapchat from './share-snapchat/share-snapchat';
import * as snapchat from './snapchat/snapchat';
import * as expandAll from './expand-all/expand-all';
import * as accessibility from './accessibility/accessibility';
import * as features from './features/features';
import * as update from './update/update';
import * as distance from './distance/distance';
import * as coronavirus from './coronavirus/coronavirus';
import * as coughing from './coughing/coughing';
import * as cover from './cover/cover';
import * as cubes from './cubes/cubes';
import * as handHeart from './hand-heart/hand-heart';
import * as handWatter from './hand-watter/hand-watter';
import * as labTests from './lab-tests/lab-tests';
import * as mask from './mask/mask';
import * as noCoughing from './no-coughing/no-coughing';
import * as noHandshake from './no-handshake/no-handshake';
import * as noVirus from './no-virus/no-virus';
import * as procurement from './procurement/procurement';
import * as project from './project/project';
import * as soap from './soap/soap';
import * as stayHome from './stay-home/stay-home';
import * as teleworking from './teleworking/teleworking';
import * as testing from './testing/testing';
import * as testingAlt from './testing-alt/testing-alt';
import * as virus from './virus/virus';
import * as viruses from './viruses/viruses';
import * as wash from './wash/wash';
import * as amusement from './amusement/amusement';
import * as balloons from './balloons/balloons';
import * as bargeShip from './barge-ship/barge-ship';
import * as bike from './bike/bike';
import * as boat from './boat/boat';
import * as bridge from './bridge/bridge';
import * as bridgeAlt from './bridge-alt/bridge-alt';
import * as bus from './bus/bus';
import * as busAlt from './bus-alt/bus-alt';
import * as car from './car/car';
import * as carAlt from './car-alt/car-alt';
import * as casino from './casino/casino';
import * as coffee from './coffee/coffee';
import * as cruiseShip from './cruise-ship/cruise-ship';
import * as dices from './dices/dices';
import * as directions from './directions/directions';
import * as entertainment from './entertainment/entertainment';
import * as family from './family/family';
import * as familyAlt from './family-alt/family-alt';
import * as fastfood from './fastfood/fastfood';
import * as ferry from './ferry/ferry';
import * as fitness from './fitness/fitness';
import * as fitnessAlt from './fitness-alt/fitness-alt';
import * as hair from './hair/hair';
import * as hairSalon from './hair-salon/hair-salon';
import * as highway from './highway/highway';
import * as museum from './museum/museum';
import * as museumAlt from './museum-alt/museum-alt';
import * as noTravel from './no-travel/no-travel';
import * as paddleBoat from './paddle-boat/paddle-boat';
import * as party from './party/party';
import * as places from './places/places';
import * as rail from './rail/rail';
import * as restaurant from './restaurant/restaurant';
import * as road from './road/road';
import * as rv from './rv/rv';
import * as sailShip from './sail-ship/sail-ship';
import * as scooter from './scooter/scooter';
import * as ship from './ship/ship';
import * as speedtrain from './speedtrain/speedtrain';
import * as suv from './suv/suv';
import * as temple from './temple/temple';
import * as train from './train/train';
import * as trolleybus from './trolleybus/trolleybus';
import * as truck from './truck/truck';
import * as truckAlt from './truck-alt/truck-alt';
import * as van from './van/van';
import * as yacht from './yacht/yacht';
import * as zoo from './zoo/zoo';
import * as zooAlt from './zoo-alt/zoo-alt';
import * as air from './air/air';
import * as airPollution from './air-pollution/air-pollution';
import * as airQuality from './air-quality/air-quality';
import * as anchor from './anchor/anchor';
import * as badminton from './badminton/badminton';
import * as baseball from './baseball/baseball';
import * as basketball from './basketball/basketball';
import * as bath from './bath/bath';
import * as billiards from './billiards/billiards';
import * as bowling from './bowling/bowling';
import * as careTweezers from './care-tweezers/care-tweezers';
import * as church from './church/church';
import * as externalLink from './external-link/external-link';
import * as football from './football/football';
import * as golf from './golf/golf';
import * as nailPolish from './nail-polish/nail-polish';
import * as personalCare from './personal-care/personal-care';
import * as soccer from './soccer/soccer';
import * as tennis from './tennis/tennis';
import * as audience from './audience/audience';
import * as maskLight from './mask-light/mask-light';
import * as maskDark from './mask-dark/mask-dark';
import * as barsUp from './bars-up/bars-up';
import * as vaccineCheck from './vaccine-check/vaccine-check';
import * as onlineGraduate from './online-graduate/online-graduate';
import * as textbook from './textbook/textbook';
import * as onlineEducation from './online-education/online-education';
import * as userDesktopInstructor from './user-desktop-instructor/user-desktop-instructor';
import * as certificateClick from './certificate-click/certificate-click';
import * as userLaptop from './user-laptop/user-laptop';
import * as desktopChecklist from './desktop-checklist/desktop-checklist';
import * as userHeadphone from './user-headphone/user-headphone';
import * as homeEducation from './home-education/home-education';
import * as cellphoneTouch from './cellphone-touch/cellphone-touch';
import * as homeGraduate from './home-graduate/home-graduate';
import * as mobileTextbook from './mobile-textbook/mobile-textbook';
import * as onlineModule from './online-module/online-module';
import * as teams from './teams/teams';
import * as userDesk from './user-desk/user-desk';
import * as google from './google/google';
import * as graduatePointer from './graduate-pointer/graduate-pointer';
import * as desktopVideoModule from './desktop-video-module/desktop-video-module';
import * as mobileGraduate from './mobile-graduate/mobile-graduate';
import * as pharmacy from './pharmacy/pharmacy';
import * as envelopeChecklist from './envelope-checklist/envelope-checklist';
import * as spartanHelmet from './spartan-helmet/spartan-helmet';
import * as cartDelivered from './cart-delivered/cart-delivered';
import * as medicalShipped from './medical-shipped/medical-shipped';
import * as vaccine from './vaccine/vaccine';
import * as team from './team/team';
import * as vaccinePatient from './vaccine-patient/vaccine-patient';
import * as improvements from './improvements/improvements';
import * as cloudNetwork from './cloud-network/cloud-network';
import * as technologyReuse from './technology-reuse/technology-reuse';
import * as barsUpward from './bars-upward/bars-upward';
import * as onlineHelp from './online-help/online-help';
import * as speechDialog from './speech-dialog/speech-dialog';
import * as pdfText from './pdf-text/pdf-text';
import * as github from './github/github';
import * as usersCheckMark from './users-check-mark/users-check-mark';
import * as usersHuddle from './users-huddle/users-huddle';
import * as quotationMark from './quotation-mark/quotation-mark';
import * as water from './water/water';
import * as windPower from './wind-power/wind-power';
import * as connection from './connection/connection';
import * as transport from './transport/transport';
import * as maintenance from './maintenance/maintenance';
import * as warningDiamond from './warning-diamond/warning-diamond';
import * as pipeAngle from './pipe-angle/pipe-angle';
import * as pipe from './pipe/pipe';
import * as bullet from './bullet/bullet';
import * as dot from './dot/dot';

// This adds the CAWeb Icon to the Modules Library.
const addCAWebModuleIcon = ( icons: object[] ) => {
	return {
		...icons, // This is important. Without this, all other icons will be overwritten.
		[caweb.name]: caweb
	};
};

// Add module icons to the icon library.
addFilter( 'divi.iconLibrary.icon.map', 'caweb.addCAWebModuleIcon', addCAWebModuleIcon );

// the divi filters aren't all working yet, so this is a good place to add icons to the iconList
addAction( 
	'divi.visualBuilder.registerStores.after',
	'caweb.iconList',
	( arr: object[] ) => {
		let cawebIconList = [
			arrowUp.data,
			arrowDown.data,
			arrowLeft.data,
			arrowRight.data,
			arrowLeftUp.data,
			arrowRightUp.data,
			arrowRightDown.data,
			arrowLeftDown.data,
			arrowUpDown.data,
			arrowUpDownAlt.data,
			arrowLeftRightAlt.data,
			arrowLeftRight.data,
			arrowExpandAlt2.data,
			arrowExpandAlt.data,
			arrowCondense.data,
			arrowExpand.data,
			arrowMove.data,
			caretUp.data,
			caretDown.data,
			caretLeft.data,
			caretRight.data,
			caretTwoUp.data,
			caretTwoDown.data,
			caretTwoLeft.data,
			caretTwoRight.data,
			caretLineUp.data,
			caretLineDown.data,
			caretLineLeft.data,
			caretLineRight.data,
			caretLineTwoUp.data,
			caretLineTwoDown.data,
			caretLineTwoLeft.data,
			caretLineTwoRight.data,
			triangleUp.data,
			triangleDown.data,
			triangleLeft.data,
			triangleRight.data,
			triangleLineUp.data,
			triangleLineDown.data,
			triangleLineLeft.data,
			triangleLineRight.data,
			arrowBack.data,
			minusMark.data,
			plusMark.data,
			closeMark.data,
			checkMark.data,
			minusLine.data,
			plusLine.data,
			closeLine.data,
			checkLine.data,
			iconZoomOutAlt.data,
			iconZoomInAlt.data,
			searchRight.data,
			iconBoxEmpty.data,
			iconBoxSelected.data,
			collapse.data,
			expand.data,
			iconBoxChecked.data,
			iconCircleEmpty.data,
			iconCircleSlelected.data,
			iconStopAlt2.data,
			iconStop.data,
			iconPauseAlt2.data,
			iconPause.data,
			iconMenu.data,
			iconMenuSquareAlt2.data,
			iconMenuCircleAlt2.data,
			iconUl.data,
			iconOl.data,
			iconAdjustHoriz.data,
			iconAdjustVert.data,
			iconDocumentAlt.data,
			iconDocumentsAlt.data,
			pencil.data,
			iconPencilEditAlt.data,
			pencilEdit.data,
			iconFolderAlt.data,
			iconFolderOpenAlt.data,
			iconFolderAddAlt.data,
			toggle.data,
			countdown.data,
			iconErrorCircleAlt.data,
			iconErrorTriangleAlt.data,
			iconCommentAlt.data,
			iconChatAlt.data,
			iconVolMuteAlt.data,
			iconVolumeLowAlt.data,
			iconVolumeHighAlt.data,
			iconQuotations.data,
			iconQuotationsAlt2.data,
			iconClockAlt.data,
			iconLockAlt.data,
			cta.data,
			filteredPortfolio.data,
			blurb.data,
			circleCounter.data,
			numberCounter.data,
			pricingTable.data,
			portfolio.data,
			tabs.data,
			subscribe.data,
			slider.data,
			sidebar.data,
			share.data,
			divider.data,
			header.data,
			beaker3.data,
			beaker4.data,
			beaker5.data,
			caweb.data,
			candleAlt.data,
			iconLockOpenAlt.data,
			iconKeyAlt.data,
			iconCloudAlt.data,
			iconCloudUploadAlt.data,
			iconCloudDownloadAlt.data,
			iconLightbulbAlt.data,
			iconGiftAlt.data,
			iconHouseAlt.data,
			science.data,
			iconLaptop.data,
			iconCameraAlt.data,
			iconMailAlt.data,
			iconConeAlt.data,
			iconRibbonAlt.data,
			iconBagAlt.data,
			iconCreditcard.data,
			iconCartAlt.data,
			iconPaperclip.data,
			iconTagAlt.data,
			iconTagsAlt.data,
			iconTrashAlt.data,
			iconCursorAlt.data,
			iconMicAlt.data,
			iconCompassAlt.data,
			iconPinAlt.data,
			iconPushpinAlt.data,
			iconMapAlt.data,
			iconDrawerAlt.data,
			iconToolboxAlt.data,
			iconBookAlt.data,
			iconCalendar.data,
			film.data,
			table.data,
			iconContactsAlt.data,
			iconHeadphones.data,
			iconRefresh.data,
			iconLinkAlt.data,
			iconLink.data,
			iconLoading.data,
			iconBlocked.data,
			iconArchiveAlt.data,
			iconHeartAlt.data,
			iconStarAlt.data,
			iconStarHalfAlt.data,
			iconStarHalf.data,
			tools.data,
			iconCog.data,
			iconCogs.data,
			arrowFillUp.data,
			arrowFillDown.data,
			arrowFillLeft.data,
			arrowFillRight.data,
			arrowFillLeftUp.data,
			arrowFillRightUp.data,
			arrowFillRightDown.data,
			arrowFillLeftDown.data,
			arrowCondenseAlt.data,
			arrowExpandAlt3.data,
			caretFillUp.data,
			caretFillDown.data,
			caretFillLeft.data,
			caretFillRight.data,
			caretFillTwoUp.data,
			caretFillTwoDown.data,
			caretFillTwoLeft.data,
			caretFillTwoRight.data,
			triangleFillUp.data,
			triangleFillDown.data,
			triangleFillLeft.data,
			triangleFillRight.data,
			minusFill.data,
			plusFill.data,
			closeFill.data,
			checkFill.data,
			iconZoomOut.data,
			iconZoomIn.data,
			iconStopAlt.data,
			iconMenuSquareAlt.data,
			iconMenuCircleAlt.data,
			iconDocument.data,
			iconDocuments.data,
			iconPencilAlt.data,
			iconFolder.data,
			folder.data,
			iconFolderAdd.data,
			iconFolderUpload.data,
			iconFolderDownload.data,
			iconErrorCircle.data,
			warningFill.data,
			warningTriangle.data,
			questionFill.data,
			iconComment.data,
			iconChat.data,
			iconVolMute.data,
			iconVolumeLow.data,
			volume.data,
			quoteFill.data,
			iconClock.data,
			iconLock.data,
			iconLockOpen.data,
			iconKey.data,
			iconCloud.data,
			iconCloudUpload.data,
			iconCloudDownload.data,
			lightbulb.data,
			iconGift.data,
			iconHouse.data,
			iconMail.data,
			iconCone.data,
			iconRibbon.data,
			iconBag.data,
			iconCart.data,
			iconTag.data,
			tags.data,
			iconTrash.data,
			iconCursor.data,
			mic.data,
			iconCompass.data,
			location.data,
			pushpin.data,
			map.data,
			drawer.data,
			book.data,
			contacts.data,
			archive.data,
			iconHeart.data,
			grid.data,
			music.data,
			iconPauseAlt.data,
			iconPhone.data,
			iconUpload.data,
			iconDownload.data,
			barCounters.data,
			audio.data,
			accordion.data,
			socialGoogleplus.data,
			socialTumblr.data,
			socialTumbleupon.data,
			socialWordpress.data,
			socialDribbble.data,
			socialDeviantart.data,
			socialMyspace.data,
			socialSkype.data,
			socialPicassa.data,
			socialGoogledrive.data,
			socialFlickr.data,
			socialBlogger.data,
			socialSpotify.data,
			socialDelicious.data,
			socialFacebookCircle.data,
			socialTwitterCircle.data,
			socialPinterestCircle.data,
			socialGoogleplusCircle.data,
			socialTumblrCircle.data,
			socialStumbleuponCircle.data,
			socialWordpressCircle.data,
			socialInstagramCircle.data,
			socialDribbbleCircle.data,
			socialVimeoCircle.data,
			socialLinkedinCircle.data,
			socialRssCircle.data,
			socialDeviantartCircle.data,
			socialShareCircle.data,
			socialMyspaceCircle.data,
			socialSkypeCircle.data,
			socialYoutubeCircle.data,
			socialPicassaCircle.data,
			socialGoogledriveAlt2.data,
			socialFlickrCircle.data,
			socialBloggerCircle.data,
			socialSpotifyCircle.data,
			socialDeliciousCircle.data,
			socialTumblrSquare.data,
			socialStumbleuponSquare.data,
			socialWordpressSquare.data,
			socialInstagramSquare.data,
			socialDribbbleSquare.data,
			socialRssSquare.data,
			socialDeviantartSquare.data,
			socialShareSquare.data,
			socialMyspaceSquare.data,
			socialSkypeSquare.data,
			socialPicassaSquare.data,
			socialGoogledriveSquare.data,
			socialFlickrSquare.data,
			socialBloggerSquare.data,
			socialSpotifySquare.data,
			socialDeliciousSquare.data,
			wallet.data,
			iconShieldAlt.data,
			iconPercentAlt.data,
			iconPensAlt.data,
			iconMugAlt.data,
			iconLikeAlt.data,
			iconGlobeAlt.data,
			flowchart.data,
			iconIdAlt.data,
			hourglass.data,
			iconGlobe.data,
			globe.data,
			iconFloppyAlt.data,
			drive.data,
			iconClipboard.data,
			calculator.data,
			iconFloppy.data,
			iconEasel.data,
			iconDrive.data,
			iconDislike.data,
			iconDatareport.data,
			iconCurrency.data,
			iconCalulator.data,
			iconBuilding.data,
			iconDislikeAlt.data,
			currency.data,
			iconBriefcaseAlt.data,
			iconTarget.data,
			iconShield.data,
			searching.data,
			iconRook.data,
			iconPuzzleAlt.data,
			iconPercent.data,
			building.data,
			iconBriefcase.data,
			iconBalance.data,
			iconWallet.data,
			iconSearch.data,
			iconPuzzle.data,
			iconPrinter.data,
			iconPens.data,
			iconMug.data,
			iconLike.data,
			iconId.data,
			iconId2.data,
			iconFlowchart.data,
			logo.data,
			home.data,
			menu.data,
			apps.data,
			search.data,
			chat.data,
			capitol.data,
			state.data,
			phone.data,
			email.data,
			calendar.data,
			bear.data,
			lawEnforcement.data,
			justiceLegal.data,
			atSign.data,
			attachment.data,
			zippedFile.data,
			powerpoint.data,
			excel.data,
			word.data,
			pdf.data,
			share2.data,
			facebook.data,
			linkedin.data,
			youtube.data,
			twitter.data,
			pinterest.data,
			vimeo.data,
			instagram.data,
			flickr.data,
			microsoft.data,
			apple.data,
			android.data,
			computer.data,
			tablet.data,
			smartphone.data,
			roadways.data,
			travelCar.data,
			travelAir.data,
			truckDelivery.data,
			construction.data,
			barChart.data,
			pieChart.data,
			graph.data,
			server.data,
			download.data,
			cloudDownload.data,
			cloudUpload.data,
			shield.data,
			fire.data,
			binoculars.data,
			compass.data,
			sos.data,
			shoppingCart.data,
			videoCamera.data,
			camera.data,
			green.data,
			loudSpeaker.data,
			audio2.data,
			print.data,
			medical.data,
			zoomOut.data,
			zoomIn.data,
			important.data,
			chatBubbles.data,
			call.data,
			people.data,
			person.data,
			userId.data,
			paymentCard.data,
			skipBackwards.data,
			play.data,
			pause.data,
			skipForward.data,
			mail.data,
			image.data,
			house.data,
			gear.data,
			tool.data,
			time.data,
			cal.data,
			checkList.data,
			document.data,
			clipboard.data,
			page.data,
			readBook.data,
			ccCopyright.data,
			caCapitol.data,
			caState.data,
			favorite.data,
			rss.data,
			roadPin.data,
			onlineServices.data,
			link.data,
			magnifyGlass.data,
			key.data,
			lock.data,
			info.data,
			carouselPrev.data,
			carouselNext.data,
			arrowPrev.data,
			arrowNext.data,
			menuToggleClosed.data,
			menuToggleOpen.data,
			carouselPause.data,
			googlePlus.data,
			contactUs.data,
			chatBubble.data,
			infoBubble.data,
			shareButton.data,
			shareFacebook.data,
			shareEmail.data,
			shareFlickr.data,
			shareTwitter.data,
			shareLinkedin.data,
			shareGoogleplus.data,
			shareInstagram.data,
			sharePinterest.data,
			shareVimeo.data,
			shareYoutube.data,
			gears.data,
			briefcase.data,
			idea.data,
			graduate.data,
			images.data,
			infoLine.data,
			importantLine.data,
			carouselPlay.data,
			questionLine.data,
			question.data,
			filter.data,
			calBear.data,
			hours.data,
			hoursSecurity.data,
			albums.data,
			brain.data,
			certificate.data,
			certificateCheck.data,
			charge.data,
			chargeCycle.data,
			chargeUnits.data,
			city.data,
			clock.data,
			cloudGear.data,
			biohazard.data,
			malware.data,
			cloudServices.data,
			cloudSync.data,
			code.data,
			ear.data,
			earSlash.data,
			eye.data,
			eyeSlash.data,
			file.data,
			fileAudio.data,
			fileCertificate.data,
			fileCheck.data,
			fileCode.data,
			fileCsv.data,
			fileDownload.data,
			fileExcel.data,
			fileExport.data,
			fileImport.data,
			fileInvoice.data,
			fileMedical.data,
			fileMedicalAlt.data,
			filePdf.data,
			filePowerpoint.data,
			filePrescription.data,
			fileUpload.data,
			fileVideo.data,
			fileWord.data,
			fileZip.data,
			filterSolid.data,
			fingerprint.data,
			fingerprintCheck.data,
			hand.data,
			handMoney.data,
			handshake.data,
			institute.data,
			medicalBubble.data,
			medicalCare.data,
			medicalCase.data,
			medicalClinic.data,
			medicalCross.data,
			medicalDoctor.data,
			medicalHeart.data,
			medicalPills.data,
			mobile.data,
			proServices.data,
			puzzle.data,
			puzzlePiece.data,
			recycle.data,
			responsive.data,
			responsiveAlt.data,
			securityNetwork.data,
			securitySystem.data,
			shieldCheck.data,
			thumbUp.data,
			trophy.data,
			users.data,
			usersAlt.data,
			usersDialog.data,
			usersInteraction.data,
			video.data,
			radiation.data,
			chemicalHazard.data,
			danger.data,
			doNotSign.data,
			earthquake.data,
			quakeHouse.data,
			quakeHazard.data,
			electricityHazard.data,
			flood.data,
			hazard.data,
			hurricane.data,
			seaLevelRise.data,
			severeWeather.data,
			stopFire.data,
			stopHand.data,
			tornado.data,
			tsunami.data,
			volcano.data,
			warningCircle.data,
			warningSquare.data,
			tent.data,
			campfire.data,
			dam.data,
			downloadCloud.data,
			uploadCloud.data,
			seaLevelRiseAlt.data,
			tsunamiAlt.data,
			collapseAll.data,
			signLanguage.data,
			drag.data,
			agriculture.data,
			cannabis.data,
			angry.data,
			happy.data,
			visa.data,
			mastercard.data,
			amexcard.data,
			applePay.data,
			discovercard.data,
			paypal.data,
			chrome.data,
			firefox.data,
			ie.data,
			opera.data,
			safari.data,
			bell.data,
			bookmark.data,
			books.data,
			reader.data,
			palette.data,
			glass.data,
			heart.data,
			digging.data,
			gasPump.data,
			ideaAlt.data,
			medal.data,
			smoking.data,
			noSmoking.data,
			shareSnapchat.data,
			snapchat.data,
			expandAll.data,
			accessibility.data,
			features.data,
			update.data,
			distance.data,
			coronavirus.data,
			coughing.data,
			cover.data,
			cubes.data,
			handHeart.data,
			handWatter.data,
			labTests.data,
			mask.data,
			noCoughing.data,
			noHandshake.data,
			noVirus.data,
			procurement.data,
			project.data,
			soap.data,
			stayHome.data,
			teleworking.data,
			testing.data,
			testingAlt.data,
			virus.data,
			viruses.data,
			wash.data,
			amusement.data,
			balloons.data,
			bargeShip.data,
			bike.data,
			boat.data,
			bridge.data,
			bridgeAlt.data,
			bus.data,
			busAlt.data,
			car.data,
			carAlt.data,
			casino.data,
			coffee.data,
			cruiseShip.data,
			dices.data,
			directions.data,
			entertainment.data,
			family.data,
			familyAlt.data,
			fastfood.data,
			ferry.data,
			fitness.data,
			fitnessAlt.data,
			hair.data,
			hairSalon.data,
			highway.data,
			museum.data,
			museumAlt.data,
			noTravel.data,
			paddleBoat.data,
			party.data,
			places.data,
			rail.data,
			restaurant.data,
			road.data,
			rv.data,
			sailShip.data,
			scooter.data,
			ship.data,
			speedtrain.data,
			suv.data,
			temple.data,
			train.data,
			trolleybus.data,
			truck.data,
			truckAlt.data,
			van.data,
			yacht.data,
			zoo.data,
			zooAlt.data,
			air.data,
			airPollution.data,
			airQuality.data,
			anchor.data,
			badminton.data,
			baseball.data,
			basketball.data,
			bath.data,
			billiards.data,
			bowling.data,
			careTweezers.data,
			church.data,
			externalLink.data,
			football.data,
			golf.data,
			nailPolish.data,
			personalCare.data,
			soccer.data,
			tennis.data,
			audience.data,
			maskLight.data,
			maskDark.data,
			barsUp.data,
			vaccineCheck.data,
			onlineGraduate.data,
			textbook.data,
			onlineEducation.data,
			userDesktopInstructor.data,
			certificateClick.data,
			userLaptop.data,
			desktopChecklist.data,
			userHeadphone.data,
			homeEducation.data,
			cellphoneTouch.data,
			homeGraduate.data,
			mobileTextbook.data,
			onlineModule.data,
			teams.data,
			userDesk.data,
			google.data,
			graduatePointer.data,
			desktopVideoModule.data,
			mobileGraduate.data,
			pharmacy.data,
			envelopeChecklist.data,
			spartanHelmet.data,
			cartDelivered.data,
			medicalShipped.data,
			vaccine.data,
			team.data,
			vaccinePatient.data,
			improvements.data,
			cloudNetwork.data,
			technologyReuse.data,
			barsUpward.data,
			onlineHelp.data,
			speechDialog.data,
			pdfText.data,
			github.data,
			usersCheckMark.data,
			usersHuddle.data,
			quotationMark.data,
			water.data,
			windPower.data,
			connection.data,
			transport.data,
			maintenance.data,
			warningDiamond.data,
			pipeAngle.data,
			pipe.data,
			bullet.data,
			dot.data
		];

		iconList.push( ...cawebIconList );

	}
);
