// Autogenerated file, do not edit directly

// External Dependencies.
import { omit } from 'lodash';

// WordPress Dependencies.
import { addAction, addFilter } from '@wordpress/hooks';

// Divi Dependencies.
import { registerModule } from '@divi/module-library';

// Modules.
import { ChildModule } from './Child';
import { D4Module } from './D4';
import { DynamicModule } from './Dynamic';
import { PanelModule } from './Panel';
import { ParentModule } from './Parent';
import { StaticModule } from './Static';

// Register modules.
addAction('divi.moduleLibrary.registerModuleLibraryStore.after', 'caweb.registerModuleLibraryStore', () => {
	registerModule( ChildModule.metadata, omit( ChildModule, 'metadata' ) );
	registerModule( D4Module.metadata, omit( D4Module, 'metadata' ) );
	registerModule( DynamicModule.metadata, omit( DynamicModule, 'metadata' ) );
	registerModule( PanelModule.metadata, omit( PanelModule, 'metadata' ) );
	registerModule( ParentModule.metadata, omit( ParentModule, 'metadata' ) );
	registerModule( StaticModule.metadata, omit( StaticModule, 'metadata' ) );
});
